# Generated by Django 4.1.2 on 2022-11-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=20)),
                ('surname', models.CharField(default='surname', max_length=20)),
                ('email', models.EmailField(default='email', max_length=254)),
                ('company', models.CharField(default='company', max_length=30)),
                ('message', models.TextField(default='message', max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('message', models.TextField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Сustomer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
